module.exports = {
    // App Settings
    MONGO_URI: process.env.MONGO_URI || 'localhost:27017',
    TOKEN_SECRET: process.env.TOKEN_SECRET || 'YOUR_UNIQUE_JWT_TOKEN_SECRET',

    // OAuth 2.0
    FACEBOOK_SECRET: process.env.FACEBOOK_SECRET || 'c1f8847b1a6db54600119fd8fbe628fb',
    FOURSQUARE_SECRET: process.env.FOURSQUARE_SECRET || 'YOUR_FOURSQUARE_CLIENT_SECRET',
    GOOGLE_SECRET: process.env.GOOGLE_SECRET || 'OxZOqtJs1JFAHVOQxG9UVIbp',
    GITHUB_SECRET: process.env.GITHUB_SECRET || '285979848d44c51d21fd4d27ea870b4e3ab51bb8',
    INSTAGRAM_SECRET: process.env.INSTAGRAM_SECRET || 'YOUR_INSTAGRAM_CLIENT_SECRET',
    LINKEDIN_SECRET: process.env.LINKEDIN_SECRET || 'U9WwzgJo7d5mLdaO',
    TWITCH_SECRET: process.env.TWITCH_SECRET || 'YOUR_TWITCH_CLIENT_SECRET',
    WINDOWS_LIVE_SECRET: process.env.WINDOWS_LIVE_SECRET || 'YOUR_MICROSOFT_CLIENT_SECRET',
    YAHOO_SECRET: process.env.YAHOO_SECRET || 'YOUR_YAHOO_CLIENT_SECRET',
    BITBUCKET_SECRET: process.env.BITBUCKET_SECRET || 'YOUR_BITBUCKET_CLIENT_SECRET',
    SPOTIFY_SECRET: process.env.SPOTIFY_SECRET || 'YOUR_SPOTIFY_CLIENT_SECRET',

    // OAuth 1.0
    TWITTER_KEY: process.env.TWITTER_KEY || 'tsTCARpMX2c1TT3vdrnUpn73C',
    TWITTER_SECRET: process.env.TWITTER_SECRET || '9K6SiDWeqwJOdfHvijQC1ZAwWgJbODY3XI071tTFWxVRoPg8ol'
};